#! /bin/sh 

echo Starting all beacon daemons 
echo    This won\'t exit until beacon-startup is done
echo    Use journalctl -u beacon-startup to see output
systemctl isolate beacon.target
echo Done, everything is hopefully running now 
systemctl status beacon-startup.target
